In [ ]:
# Flight Operations Data Analysis

## Day 10 - Python Programming Internship

This notebook performs a complete data analysis workflow on a Flight Operations dataset using Python and Pandas.

### Objectives

- Load and understand the flight operations dataset
- Inspect its structure and statistics
- Select and filter relevant records
- Sort flight records
- Perform grouping and aggregation
- Apply suitable data transformations
- Identify patterns and key findings
- Write meaningful observations based on the analysis

SyntaxError: invalid syntax (3218518015.py, line 5)

In [ ]:
import pandas as pd
import numpy as np
from google.colab import files

# Upload the Flight Operations CSV file
uploaded = files.upload()

# Get the uploaded filename
file_name = next(iter(uploaded))

# Load the dataset
df = pd.read_csv(file_name)

print("Dataset loaded successfully!")
print("File:", file_name)

Saving Day10_Flight_Operations_Dataset.csv to Day10_Flight_Operations_Dataset (1).csv
Dataset loaded successfully!
File: Day10_Flight_Operations_Dataset (1).csv

In [ ]:
## 1. Dataset Overview

Let's inspect the structure, dimensions, columns, data types, and statistical characteristics of the Flight Operations dataset.

SyntaxError: unterminated string literal (detected at line 3) (1802038712.py, line 3)

In [ ]:
print("Dataset Shape:", df.shape)

print("\nColumn Names:")
print(df.columns.tolist())

print("\nFirst 5 Rows:")
display(df.head())

print("\nLast 5 Rows:")
display(df.tail())

print("\nRandom Sample:")
display(df.sample(5))

print("\nDataset Information:")
df.info()

print("\nDescriptive Statistics:")
display(df.describe())

Dataset Shape: (180, 17)

Column Names:
['Flight_ID', 'Flight_Date', 'Airline', 'Origin', 'Destination', 'Aircraft', 'Travel_Class', 'Passengers', 'Seat_Capacity', 'Average_Ticket_Price', 'Delay_Minutes', 'Flight_Status', 'Weather', 'Booking_Channel', 'Avg_Baggage_Kg', 'Meal_Preference', 'Passenger_Satisfaction']

First 5 Rows:

,Flight_ID,Flight_Date,Airline,Origin,Destination,Aircraft,Travel_Class,Passengers,Seat_Capacity,Average_Ticket_Price,Delay_Minutes,Flight_Status,Weather,Booking_Channel,Avg_Baggage_Kg,Meal_Preference,Passenger_Satisfaction
0,FL0001,2026-03-23,SpiceJet,Mumbai,Bengaluru,Airbus A319,Economy,210,180,6894,50.0,Delayed,Storm,Online Travel Portal,23,No Meal,3
1,FL0002,2026-06-07,Akasa Air,Delhi,Mumbai,Boeing 737,Economy,70,210,4468,0.0,On Time,Fog,Travel Agency,16,Vegan,5
2,FL0003,2026-05-12,Air India,Kochi,Delhi,Boeing 737,Economy,67,220,4713,5.0,On Time,Rain,Travel Agency,19,No Meal,2
3,FL0004,2026-05-30,Akasa Air,Srinagar,Delhi,Airbus A319,Economy,153,220,3791,35.0,Delayed,Storm,Travel Agency,18,No Meal,2
4,FL0005,2026-02-27,Air India,Pune,Delhi,Airbus A319,Premium Economy,178,180,6505,20.0,Delayed,Cloudy,Airline Website,25,No Meal,5

Last 5 Rows:

,Flight_ID,Flight_Date,Airline,Origin,Destination,Aircraft,Travel_Class,Passengers,Seat_Capacity,Average_Ticket_Price,Delay_Minutes,Flight_Status,Weather,Booking_Channel,Avg_Baggage_Kg,Meal_Preference,Passenger_Satisfaction
175,FL0176,2026-04-10,IndiGo,Ahmedabad,Bengaluru,Airbus A320,Economy,48,189,4298,0.0,On Time,Storm,Mobile App,11,Vegetarian,5
176,FL0177,2026-02-17,Vistara,Chennai,Mumbai,Airbus A320,Business,124,180,17306,20.0,Delayed,Cloudy,Mobile App,8,No Meal,5
177,FL0178,2026-04-30,IndiGo,Delhi,Mumbai,Airbus A319,Economy,112,186,4490,110.0,Delayed,Fog,Online Travel Portal,16,Vegetarian,3
178,FL0179,2026-05-08,Vistara,Bengaluru,Kochi,Airbus A320,Economy,134,189,5413,20.0,Delayed,Rain,Online Travel Portal,9,No Meal,2
179,FL0180,2026-01-22,Akasa Air,Delhi,Mumbai,Airbus A321,Economy,144,210,3767,75.0,Delayed,Fog,Online Travel Portal,17,No Meal,5

Random Sample:

,Flight_ID,Flight_Date,Airline,Origin,Destination,Aircraft,Travel_Class,Passengers,Seat_Capacity,Average_Ticket_Price,Delay_Minutes,Flight_Status,Weather,Booking_Channel,Avg_Baggage_Kg,Meal_Preference,Passenger_Satisfaction
172,FL0173,2026-06-02,SpiceJet,Srinagar,Delhi,Airbus A319,Economy,143,189,6817,75.0,Delayed,Storm,Mobile App,20,No Meal,2
130,FL0131,2026-04-21,Air India Express,Mumbai,Bengaluru,Boeing 737,Economy,159,220,6354,0.0,On Time,Cloudy,Travel Agency,14,No Meal,5
35,FL0036,2026-02-06,Akasa Air,Delhi,Chennai,Airbus A320,Economy,113,189,3471,12.0,On Time,Rain,Online Travel Portal,15,Vegetarian,5
117,FL0118,2026-01-27,Air India Express,Jaipur,Mumbai,Airbus A320,Economy,72,210,3831,0.0,On Time,Cloudy,Travel Agency,5,Non-Vegetarian,2
5,FL0006,2026-05-20,Akasa Air,Kochi,Delhi,Airbus A319,Economy,123,220,5636,35.0,Delayed,Cloudy,Travel Agency,13,Vegetarian,2

Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180 entries, 0 to 179
Data columns (total 17 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Flight_ID               180 non-null    object
 1   Flight_Date             180 non-null    object
 2   Airline                 180 non-null    object
 3   Origin                  180 non-null    object
 4   Destination             180 non-null    object
 5   Aircraft                180 non-null    object
 6   Travel_Class            180 non-null    object
 7   Passengers              180 non-null    int64
 8   Seat_Capacity           180 non-null    int64
 9   Average_Ticket_Price    180 non-null    int64
 10  Delay_Minutes           173 non-null    float64
 11  Flight_Status           180 non-null    object
 12  Weather                 180 non-null    object
 13  Booking_Channel         180 non-null    object
 14  Avg_Baggage_Kg          180 non-null    int64
 15  Meal_Preference         180 non-null    object
 16  Passenger_Satisfaction  180 non-null    int64
dtypes: float64(1), int64(5), object(11)
memory usage: 24.0+ KB

Descriptive Statistics:

,Passengers,Seat_Capacity,Average_Ticket_Price,Delay_Minutes,Avg_Baggage_Kg,Passenger_Satisfaction
count,180.000000,180.000000,180.000000,173.000000,180.000000,180.000000
mean,122.772222,197.238889,6111.677778,19.335260,15.150000,3.494444
std,45.635651,15.408176,3615.220040,29.029712,5.705506,1.169908
min,45.000000,180.000000,1949.000000,0.000000,5.000000,2.000000
25%,78.750000,186.000000,3815.500000,0.000000,10.000000,2.000000
50%,125.000000,189.000000,5380.000000,5.000000,15.500000,3.000000
75%,162.250000,210.000000,6790.000000,20.000000,20.000000,5.000000
max,210.000000,220.000000,27832.000000,110.000000,25.000000,5.000000

In [ ]:
## 2. Data Quality Check

Before performing analysis, we check for missing values, duplicate records, and data types.

SyntaxError: invalid syntax (2445447606.py, line 3)

In [ ]:
print("Data Types:")
print(df.dtypes)

print("\nMissing Values:")
print(df.isnull().sum())

print("\nTotal Missing Values:", df.isnull().sum().sum())

print("\nDuplicate Rows:", df.duplicated().sum())

Data Types:
Flight_ID                  object
Flight_Date                object
Airline                    object
Origin                     object
Destination                object
Aircraft                   object
Travel_Class               object
Passengers                  int64
Seat_Capacity               int64
Average_Ticket_Price        int64
Delay_Minutes             float64
Flight_Status              object
Weather                    object
Booking_Channel            object
Avg_Baggage_Kg              int64
Meal_Preference            object
Passenger_Satisfaction      int64
dtype: object

Missing Values:
Flight_ID                 0
Flight_Date               0
Airline                   0
Origin                    0
Destination               0
Aircraft                  0
Travel_Class              0
Passengers                0
Seat_Capacity             0
Average_Ticket_Price      0
Delay_Minutes             7
Flight_Status             0
Weather                   0
Booking_Channel           0
Avg_Baggage_Kg            0
Meal_Preference           0
Passenger_Satisfaction    0
dtype: int64

Total Missing Values: 7

Duplicate Rows: 0

In [ ]:
# Convert Flight_Date to DateTime
df["Flight_Date"] = pd.to_datetime(df["Flight_Date"])

print("\nFlight date range:")
print("Start:", df["Flight_Date"].min())
print("End:", df["Flight_Date"].max())

Flight date range:
Start: 2026-01-03 00:00:00
End: 2026-06-29 00:00:00

In [ ]:
## 3. Data Selection, Filtering and Sorting

Pandas can be used to select relevant columns, filter records based on conditions, and sort flights to identify important operational patterns.

In [ ]:
# Select relevant flight information
selected_data = df[
    [
        "Flight_ID",
        "Airline",
        "Origin",
        "Destination",
        "Passengers",
        "Delay_Minutes",
        "Flight_Status",
        "Passenger_Satisfaction"
    ]
]

display(selected_data.head(10))

,Flight_ID,Airline,Origin,Destination,Passengers,Delay_Minutes,Flight_Status,Passenger_Satisfaction
0,FL0001,SpiceJet,Mumbai,Bengaluru,210,50.0,Delayed,3
1,FL0002,Akasa Air,Delhi,Mumbai,70,0.0,On Time,5
2,FL0003,Air India,Kochi,Delhi,67,5.0,On Time,2
3,FL0004,Akasa Air,Srinagar,Delhi,153,35.0,Delayed,2
4,FL0005,Air India,Pune,Delhi,178,20.0,Delayed,5
5,FL0006,Akasa Air,Kochi,Delhi,123,35.0,Delayed,2
6,FL0007,Air India Express,Delhi,Srinagar,178,0.0,On Time,4
7,FL0008,Air India,Delhi,Chennai,157,0.0,On Time,5
8,FL0009,Akasa Air,Delhi,Chennai,82,75.0,Delayed,4
9,FL0010,Akasa Air,Ahmedabad,Bengaluru,125,12.0,On Time,4

In [ ]:
delayed_flights = df[df["Flight_Status"] == "Delayed"]

print("Number of delayed flights:", len(delayed_flights))
display(delayed_flights.head(10))

Number of delayed flights: 59

,Flight_ID,Flight_Date,Airline,Origin,Destination,Aircraft,Travel_Class,Passengers,Seat_Capacity,Average_Ticket_Price,Delay_Minutes,Flight_Status,Weather,Booking_Channel,Avg_Baggage_Kg,Meal_Preference,Passenger_Satisfaction
0,FL0001,2026-03-23,SpiceJet,Mumbai,Bengaluru,Airbus A319,Economy,210,180,6894,50.0,Delayed,Storm,Online Travel Portal,23,No Meal,3
3,FL0004,2026-05-30,Akasa Air,Srinagar,Delhi,Airbus A319,Economy,153,220,3791,35.0,Delayed,Storm,Travel Agency,18,No Meal,2
4,FL0005,2026-02-27,Air India,Pune,Delhi,Airbus A319,Premium Economy,178,180,6505,20.0,Delayed,Cloudy,Airline Website,25,No Meal,5
5,FL0006,2026-05-20,Akasa Air,Kochi,Delhi,Airbus A319,Economy,123,220,5636,35.0,Delayed,Cloudy,Travel Agency,13,Vegetarian,2
8,FL0009,2026-01-25,Akasa Air,Delhi,Chennai,Airbus A320,Economy,82,210,5893,75.0,Delayed,Cloudy,Mobile App,8,Vegetarian,4
16,FL0017,2026-05-24,SpiceJet,Delhi,Chennai,Airbus A321,Economy,73,220,4256,20.0,Delayed,Rain,Travel Agency,22,Non-Vegetarian,2
17,FL0018,2026-03-09,Air India Express,Jaipur,Mumbai,Airbus A321,Economy,88,180,6133,20.0,Delayed,Clear,Travel Agency,13,Vegetarian,4
21,FL0022,2026-02-01,Vistara,Kochi,Delhi,Airbus A321,Economy,126,220,5887,75.0,Delayed,Clear,Airline Website,10,Vegetarian,2
26,FL0027,2026-02-10,SpiceJet,Bengaluru,Hyderabad,Airbus A319,Economy,169,180,3973,110.0,Delayed,Clear,Mobile App,7,Vegan,4
29,FL0030,2026-04-10,SpiceJet,Delhi,Srinagar,Airbus A321,Economy,200,210,2716,75.0,Delayed,Storm,Airline Website,10,Vegan,3

In [ ]:
high_delay_flights = df[df["Delay_Minutes"] >= 30]

print("Flights delayed by 30 minutes or more:", len(high_delay_flights))
display(
    high_delay_flights.sort_values(
        by="Delay_Minutes",
        ascending=False
    ).head(10)
)

Flights delayed by 30 minutes or more: 40

,Flight_ID,Flight_Date,Airline,Origin,Destination,Aircraft,Travel_Class,Passengers,Seat_Capacity,Average_Ticket_Price,Delay_Minutes,Flight_Status,Weather,Booking_Channel,Avg_Baggage_Kg,Meal_Preference,Passenger_Satisfaction
26,FL0027,2026-02-10,SpiceJet,Bengaluru,Hyderabad,Airbus A319,Economy,169,180,3973,110.0,Delayed,Clear,Mobile App,7,Vegan,4
146,FL0147,2026-02-18,IndiGo,Mumbai,Kolkata,Airbus A319,Premium Economy,115,210,9106,110.0,Delayed,Rain,Online Travel Portal,19,Vegetarian,5
169,FL0170,2026-06-25,IndiGo,Mumbai,Kolkata,Airbus A319,Economy,130,180,3938,110.0,Delayed,Rain,Online Travel Portal,17,No Meal,4
161,FL0162,2026-01-18,Air India,Hyderabad,Kolkata,Airbus A321,Economy,128,189,5263,110.0,Delayed,Rain,Mobile App,6,Non-Vegetarian,3
177,FL0178,2026-04-30,IndiGo,Delhi,Mumbai,Airbus A319,Economy,112,186,4490,110.0,Delayed,Fog,Online Travel Portal,16,Vegetarian,3
82,FL0083,2026-04-18,Air India Express,Lucknow,Delhi,Airbus A319,Economy,71,180,2484,110.0,Delayed,Cloudy,Online Travel Portal,22,Vegetarian,4
50,FL0051,2026-05-03,Air India,Delhi,Mumbai,Airbus A321,Economy,135,210,5129,110.0,Delayed,Rain,Online Travel Portal,17,Vegetarian,4
57,FL0058,2026-04-14,IndiGo,Hyderabad,Kolkata,Boeing 737,Premium Economy,151,210,6834,110.0,Delayed,Cloudy,Travel Agency,16,Vegetarian,4
128,FL0129,2026-01-04,SpiceJet,Lucknow,Delhi,Boeing 737,Premium Economy,67,210,5657,110.0,Delayed,Cloudy,Online Travel Portal,21,Non-Vegetarian,2
107,FL0108,2026-05-30,IndiGo,Lucknow,Delhi,Airbus A319,Premium Economy,198,180,10551,75.0,Delayed,Rain,Travel Agency,13,Vegan,2

In [ ]:
print("Top flights by passenger satisfaction:")
display(
    df.sort_values(
        by="Passenger_Satisfaction",
        ascending=False
    ).head(10)
)

Top flights by passenger satisfaction:

,Flight_ID,Flight_Date,Airline,Origin,Destination,Aircraft,Travel_Class,Passengers,Seat_Capacity,Average_Ticket_Price,Delay_Minutes,Flight_Status,Weather,Booking_Channel,Avg_Baggage_Kg,Meal_Preference,Passenger_Satisfaction
1,FL0002,2026-06-07,Akasa Air,Delhi,Mumbai,Boeing 737,Economy,70,210,4468,0.0,On Time,Fog,Travel Agency,16,Vegan,5
13,FL0014,2026-06-14,Air India,Lucknow,Delhi,Airbus A321,Economy,78,220,2744,0.0,On Time,Cloudy,Online Travel Portal,13,No Meal,5
7,FL0008,2026-04-28,Air India,Delhi,Chennai,Airbus A319,Business,157,220,14173,0.0,On Time,Fog,Airline Website,25,Vegan,5
4,FL0005,2026-02-27,Air India,Pune,Delhi,Airbus A319,Premium Economy,178,180,6505,20.0,Delayed,Cloudy,Airline Website,25,No Meal,5
19,FL0020,2026-02-01,SpiceJet,Mumbai,Kolkata,Airbus A320,Economy,125,210,5715,12.0,On Time,Fog,Travel Agency,24,Non-Vegetarian,5
14,FL0015,2026-01-21,Akasa Air,Lucknow,Delhi,Boeing 737,Economy,133,186,3911,0.0,On Time,Cloudy,Travel Agency,21,No Meal,5
12,FL0013,2026-05-14,SpiceJet,Pune,Delhi,Airbus A319,Economy,162,220,4689,0.0,On Time,Cloudy,Mobile App,6,Vegetarian,5
47,FL0048,2026-01-08,Air India,Delhi,Chennai,Airbus A321,Economy,68,210,3697,20.0,Delayed,Fog,Mobile App,16,Non-Vegetarian,5
37,FL0038,2026-03-27,Air India,Delhi,Srinagar,Airbus A320,Economy,166,210,5972,NaN,Cancelled,Rain,Travel Agency,5,Non-Vegetarian,5
41,FL0042,2026-03-12,IndiGo,Delhi,Chennai,Boeing 737,Economy,122,186,5670,12.0,On Time,Storm,Airline Website,21,Vegan,5

In [ ]:
## 4. Grouping and Aggregation

Grouping allows us to compare flight operations across airlines, travel classes, flight statuses, and other categories.

In [ ]:
airline_analysis = df.groupby("Airline").agg(
    Total_Flights=("Flight_ID", "count"),
    Total_Passengers=("Passengers", "sum"),
    Average_Passengers=("Passengers", "mean"),
    Average_Delay=("Delay_Minutes", "mean"),
    Average_Ticket_Price=("Average_Ticket_Price", "mean"),
    Average_Satisfaction=("Passenger_Satisfaction", "mean")
).sort_values(
    by="Total_Passengers",
    ascending=False
)

display(airline_analysis)

,Total_Flights,Total_Passengers,Average_Passengers,Average_Delay,Average_Ticket_Price,Average_Satisfaction
Airline,,,,,,
Vistara,37,4484,121.189189,18.628571,6265.648649,3.378378
IndiGo,32,4158,129.937500,25.031250,5931.656250,3.343750
SpiceJet,32,3929,122.781250,24.137931,6189.750000,3.531250
Akasa Air,31,3427,110.548387,14.400000,5841.000000,3.419355
Air India,24,3074,128.083333,21.260870,5083.083333,3.750000
Air India Express,24,3027,126.125000,11.291667,7388.458333,3.666667

In [ ]:
origin_analysis = df.groupby("Origin").agg(
    Total_Flights=("Flight_ID", "count"),
    Total_Passengers=("Passengers", "sum"),
    Average_Delay=("Delay_Minutes", "mean"),
    Average_Satisfaction=("Passenger_Satisfaction", "mean")
).sort_values(
    by="Total_Flights",
    ascending=False
)

display(origin_analysis)

,Total_Flights,Total_Passengers,Average_Delay,Average_Satisfaction
Origin,,,,
Delhi,43,5448,24.666667,3.441860
Mumbai,29,3616,20.620690,3.551724
Bengaluru,21,2725,10.714286,3.619048
Srinagar,15,1957,16.357143,3.266667
Kochi,14,1657,15.000000,3.500000
Ahmedabad,12,1411,11.454545,3.916667
Lucknow,11,1137,40.000000,3.181818
Pune,11,1564,5.545455,3.727273
Chennai,9,738,7.444444,3.000000
Jaipur,8,962,10.000000,3.375000
Hyderabad,7,884,51.714286,3.857143

In [ ]:
destination_analysis = df.groupby("Destination").agg(
    Total_Flights=("Flight_ID", "count"),
    Total_Passengers=("Passengers", "sum"),
    Average_Delay=("Delay_Minutes", "mean"),
    Average_Satisfaction=("Passenger_Satisfaction", "mean")
).sort_values(
    by="Total_Passengers",
    ascending=False
)

display(destination_analysis)

,Total_Flights,Total_Passengers,Average_Delay,Average_Satisfaction
Destination,,,,
Delhi,51,6315,18.877551,3.411765
Bengaluru,28,3344,13.814815,3.535714
Mumbai,30,3309,20.642857,3.333333
Kolkata,20,2567,35.650000,3.900000
Chennai,17,2011,19.000000,3.470588
Srinagar,13,1828,18.916667,3.307692
Hyderabad,13,1795,15.384615,3.769231
Kochi,8,930,3.125000,3.375000

In [ ]:
## 5. Operational Pattern Analysis

Let's examine flight status, travel class, and weather conditions to identify operational patterns.

In [ ]:
status_analysis = df.groupby("Flight_Status").agg(
    Number_of_Flights=("Flight_ID", "count"),
    Total_Passengers=("Passengers", "sum"),
    Average_Delay=("Delay_Minutes", "mean"),
    Average_Satisfaction=("Passenger_Satisfaction", "mean")
).sort_values(
    by="Number_of_Flights",
    ascending=False
)

display(status_analysis)

,Number_of_Flights,Total_Passengers,Average_Delay,Average_Satisfaction
Flight_Status,,,,
On Time,114,13890,3.464912,3.587719
Delayed,59,7314,50.000000,3.271186
Cancelled,7,895,NaN,3.857143

In [ ]:
class_analysis = df.groupby("Travel_Class").agg(
    Number_of_Flights=("Flight_ID", "count"),
    Total_Passengers=("Passengers", "sum"),
    Average_Ticket_Price=("Average_Ticket_Price", "mean"),
    Average_Satisfaction=("Passenger_Satisfaction", "mean")
).sort_values(
    by="Total_Passengers",
    ascending=False
)

display(class_analysis)

,Number_of_Flights,Total_Passengers,Average_Ticket_Price,Average_Satisfaction
Travel_Class,,,,
Economy,134,16054,4550.268657,3.462687
Premium Economy,35,4574,8736.742857,3.685714
Business,11,1471,16780.000000,3.272727

In [ ]:
weather_analysis = df.groupby("Weather").agg(
    Number_of_Flights=("Flight_ID", "count"),
    Average_Delay=("Delay_Minutes", "mean"),
    Average_Satisfaction=("Passenger_Satisfaction", "mean")
).sort_values(
    by="Average_Delay",
    ascending=False
)

display(weather_analysis)

         Number_of_Flights  Average_Delay  Average_Satisfaction
Weather
Rain                    43      22.219512              3.372093
Storm                   30      20.103448              3.166667
Cloudy                  38      20.028571              3.842105
Clear                   34      18.029412              3.352941
Fog                     35      15.794118              3.685714

In [ ]:
## 6. Key Flight Operations Statistics

Let's answer several meaningful questions using the dataset.

In [ ]:
# Overall statistics
total_flights = df["Flight_ID"].nunique()
total_passengers = df["Passengers"].sum()
average_passengers = df["Passengers"].mean()
average_delay = df["Delay_Minutes"].mean()
maximum_delay = df["Delay_Minutes"].max()
average_ticket_price = df["Average_Ticket_Price"].mean()
average_satisfaction = df["Passenger_Satisfaction"].mean()

print(f"Total Flights: {total_flights}")
print(f"Total Passengers: {total_passengers:,}")
print(f"Average Passengers per Flight: {average_passengers:.2f}")
print(f"Average Delay: {average_delay:.2f} minutes")
print(f"Maximum Delay: {maximum_delay:.2f} minutes")
print(f"Average Ticket Price: ₹{average_ticket_price:.2f}")
print(f"Average Passenger Satisfaction: {average_satisfaction:.2f}/5")

Total Flights: 180
Total Passengers: 22,099
Average Passengers per Flight: 122.77
Average Delay: 19.34 minutes
Maximum Delay: 110.00 minutes
Average Ticket Price: ₹6111.68
Average Passenger Satisfaction: 3.49/5

In [ ]:
most_delayed_airline = (
    df.groupby("Airline")["Delay_Minutes"]
    .mean()
    .sort_values(ascending=False)
)

print("Airlines ranked by average delay:")
display(most_delayed_airline)

Airlines ranked by average delay:

Airline
IndiGo               25.031250
SpiceJet             24.137931
Air India            21.260870
Vistara              18.628571
Akasa Air            14.400000
Air India Express    11.291667
Name: Delay_Minutes, dtype: float64

In [ ]:
highest_passenger_airline = (
    df.groupby("Airline")["Passengers"]
    .sum()
    .sort_values(ascending=False)
)

print("Airlines ranked by total passengers:")
display(highest_passenger_airline)

Airlines ranked by total passengers:

Airline
Vistara              4484
IndiGo               4158
SpiceJet             3929
Akasa Air            3427
Air India            3074
Air India Express    3027
Name: Passengers, dtype: int64

In [ ]:
most_common_status = df["Flight_Status"].value_counts()

print("Flight Status Distribution:")
display(most_common_status)

Flight Status Distribution:

Flight_Status
On Time      114
Delayed       59
Cancelled      7
Name: count, dtype: int64

In [ ]:
booking_analysis = df["Booking_Channel"].value_counts()

print("Booking Channel Distribution:")
display(booking_analysis)

Booking Channel Distribution:

Booking_Channel
Online Travel Portal    50
Mobile App              45
Travel Agency           44
Airline Website         41
Name: count, dtype: int64

In [ ]:
weather_delay = (
    df.groupby("Weather")["Delay_Minutes"]
    .mean()
    .sort_values(ascending=False)
)

print("Average delay by weather condition:")
display(weather_delay)

Average delay by weather condition:

Weather
Rain      22.219512
Storm     20.103448
Cloudy    20.028571
Clear     18.029412
Fog       15.794118
Name: Delay_Minutes, dtype: float64

In [ ]:
## 7. Key Observations

1. The dataset contains 180 flight records and 17 features, covering flight operations from January 3, 2026 to June 29, 2026.

2. The dataset records a total of 22,099 passengers, with an average of approximately 122.77 passengers per flight.

3. Vistara handled the highest total passenger volume with 4,484 passengers across 37 flights. However, IndiGo recorded the highest average delay among the airlines at approximately 25.03 minutes.

4. Out of 180 flights, 114 were on time, 59 were delayed, and 7 were cancelled. This shows that most flights in the dataset operated on time, although delayed operations form a significant portion of the records.

5. Rain recorded the highest average delay among the weather conditions at approximately 22.22 minutes, followed by Storm at 20.10 minutes. Fog had the lowest average delay at approximately 15.79 minutes.

6. The average delay across all flights was approximately 19.34 minutes, while the maximum recorded delay was 110 minutes, indicating considerable variation in flight punctuality.

7. The average ticket price was approximately ₹6,111.68, while the average passenger satisfaction score was 3.49 out of 5. This provides useful measures for examining the relationship between pricing, operational performance, and passenger experience.

8. The dataset contains 7 missing values and no duplicate records, indicating that the dataset is largely complete and contains no repeated flight records.

In [ ]:
## 8. Conclusion

This notebook followed a complete data analysis workflow using Pandas on the Flight Operations dataset.

The analysis included:

- Loading and understanding the dataset
- Inspecting its structure and statistical characteristics
- Checking data types, missing values, and duplicates
- Selecting relevant columns
- Filtering flight records
- Sorting flights based on operational measures
- Grouping and aggregating data by airlines, origins, destinations, travel classes, flight statuses, and weather conditions
- Calculating important operational statistics
- Identifying patterns related to delays, passenger volume, ticket prices, booking channels, and satisfaction
- Developing meaningful observations from the analysis

The analysis demonstrates how Pandas can be used to transform raw flight operation records into meaningful information for understanding airline and passenger-related patterns.